version: '3'

services:
  tik_tik_db:
    image: postgres:13
    restart: always
    volumes:
      - ./ti_updater/db:/var/app/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/app/data
    ports:
      - 5432:5432
#    network_mode: "host"
    networks:
      - test

  audience-main:
    depends_on:
      - tik_tik_db
    build:
      context: ./audience
      dockerfile: Dockerfile-main
    volumes:
      - ./log-main:/app/log
    networks:
      - test

  audience-server:
    depends_on:
      - tik_tik_db
    build:
      context: ./audience
      dockerfile: Dockerfile-server
    volumes:
      - ./log-main:/app/log
    ports:
      - "8000:8000"
    networks:
      - test

networks:
  test: