version: '3'

services:
  ti_db:
    image: postgres:13
    restart: always
    volumes:
      - ./ti_updater/db:/var/app/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/app/data
    ports:
      - 5432:5432
#    network_mode: "host"
    networks:
      - test

networks:
  test: